window.APP_DATA = {
  lexicon: {
    "af": { definition: "weg van een plaats of klaar", translation: "off / finished" },
    "afgerond": { definition: "klaargemaakt of beëindigd", translation: "finished / completed" },
    "afspraak": { definition: "plan om iemand te zien of iets te doen", translation: "appointment / arrangement" },
    "afspreken": { definition: "met iemand plannen om elkaar te zien", translation: "to meet / arrange" },
    "al": { definition: "eerder dan verwacht of nu al", translation: "already" },
    "alles": { definition: "alle dingen samen", translation: "everything" },
    "als": { definition: "op het moment dat of in het geval dat", translation: "if / when / as" },
    "altijd": { definition: "elke keer", translation: "always" },
    "arts": { definition: "dokter", translation: "doctor" },
    "bij": { definition: "dicht bij of in de buurt van", translation: "at / near / with" },
    "bijna": { definition: "net niet helemaal", translation: "almost" },
    "bellen": { definition: "telefonisch contact maken", translation: "to call" },
    "besluit": { definition: "keuze na nadenken", translation: "decision" },
    "betekent": { definition: "heeft als betekenis", translation: "means" },
    "begrijpt": { definition: "snapt", translation: "understands" },
    "belangrijk": { definition: "van grote waarde of betekenis", translation: "important" },
    "belangrijker": { definition: "meer belangrijk", translation: "more important" },
    "bedrijf": { definition: "organisatie waar mensen werken", translation: "company" },
    "bericht": { definition: "kort geschreven of gesproken boodschap", translation: "message" },
    "begonnen": { definition: "gestart", translation: "started / begun" },
    "beter": { definition: "meer goed", translation: "better" },
    "blijven": { definition: "niet weggaan of doorgaan", translation: "to stay / remain" },
    "broodje": { definition: "klein stuk brood met iets erop of ertussen", translation: "sandwich / bread roll" },
    "bureau": { definition: "werktafel of kantoor", translation: "desk / office" },
    "collega": { definition: "persoon met wie je werkt", translation: "colleague" },
    "daar": { definition: "op die plaats", translation: "there" },
    "daaraan": { definition: "aan dat", translation: "about that / to that" },
    "daarna": { definition: "na dat moment", translation: "after that" },
    "dan": { definition: "op dat moment of daarna", translation: "then / than" },
    "dat": { definition: "wijst naar iets of een hele zin", translation: "that" },
    "deadline": { definition: "de uiterste tijd waarop iets klaar moet zijn", translation: "deadline" },
    "de": { definition: "lidwoord bij een zelfstandig naamwoord", translation: "the" },
    "denken": { definition: "iets in je hoofd overwegen", translation: "to think" },
    "denkt": { definition: "heeft een idee of mening", translation: "thinks" },
    "dezelfde": { definition: "precies gelijk", translation: "the same" },
    "dochter": { definition: "vrouwelijk kind", translation: "daughter" },
    "doen": { definition: "iets uitvoeren", translation: "to do" },
    "dokter": { definition: "arts", translation: "doctor" },
    "drie": { definition: "het getal na twee", translation: "three" },
    "druk": { definition: "veel spanning of veel activiteit", translation: "pressure / busy" },
    "een": { definition: "lidwoord of het getal 1", translation: "a / an / one" },
    "eerlijk": { definition: "de waarheid zeggend", translation: "honest" },
    "eerst": { definition: "voor iets anders", translation: "first" },
    "eten": { definition: "voedsel nemen", translation: "to eat / food" },
    "extra": { definition: "meer dan normaal", translation: "extra" },
    "fijn": { definition: "prettig", translation: "nice / pleasant" },
    "folder": { definition: "klein informatief boekje", translation: "leaflet / brochure" },
    "gaat": { definition: "beweegt zich of verloopt", translation: "goes" },
    "gaan": { definition: "zich verplaatsen", translation: "to go" },
    "gaarne": { definition: "met plezier", translation: "gladly" },
    "gehad": { definition: "eerder gehad of meegemaakt", translation: "had" },
    "gegeten": { definition: "eten genomen", translation: "eaten" },
    "geholpen": { definition: "ondersteund", translation: "helped" },
    "geen": { definition: "niet één / helemaal niet", translation: "no / none" },
    "gekregen": { definition: "ontvangen", translation: "received / got" },
    "gekund": { definition: "mogelijk geweest", translation: "been able to" },
    "gelukkig": { definition: "blij of gunstig", translation: "happy / fortunately" },
    "geslapen": { definition: "rust genomen in slaap", translation: "slept" },
    "gesprek": { definition: "praten met elkaar", translation: "conversation" },
    "gestuurd": { definition: "verzonden", translation: "sent" },
    "gezellig": { definition: "prettig en warm om samen te zijn", translation: "cozy / gezellig" },
    "goed": { definition: "zoals het hoort of prettig", translation: "good / well" },
    "grote": { definition: "niet klein", translation: "big / large" },
    "griep": { definition: "ziekte met koorts en pijn", translation: "flu" },
    "haar": { definition: "van haar / haar op het hoofd", translation: "her / hair" },
    "halen": { definition: "pakken of bereiken", translation: "to get / reach" },
    "half": { definition: "de helft van iets", translation: "half" },
    "hallo": { definition: "groet bij contact", translation: "hello" },
    "hart": { definition: "orgaan dat bloed pompt", translation: "heart" },
    "heeft": { definition: "bezit of ervaart", translation: "has" },
    "heb": { definition: "eerste persoon van hebben", translation: "have" },
    "hebben": { definition: "bezitten of ervaren", translation: "to have" },
    "heel": { definition: "erg of volledig", translation: "very / whole" },
    "hem": { definition: "voornaamwoord voor een man", translation: "him" },
    "het": { definition: "lidwoord of voornaamwoord", translation: "the / it" },
    "hier": { definition: "op deze plaats", translation: "here" },
    "hij": { definition: "voornaamwoord voor een man", translation: "he" },
    "huis": { definition: "plek waar je woont", translation: "house / home" },
    "huisarts": { definition: "dokter voor algemene zorg", translation: "general practitioner" },
    "hun": { definition: "van hen", translation: "their" },
    "ik": { definition: "eerste persoon enkelvoud", translation: "I" },
    "in": { definition: "binnen", translation: "in" },
    "is": { definition: "vorm van zijn", translation: "is" },
    "ja": { definition: "positief antwoord", translation: "yes" },
    "kan": { definition: "mogelijk zijn", translation: "can" },
    "klein": { definition: "niet groot", translation: "small" },
    "klant": { definition: "persoon of bedrijf dat iets koopt", translation: "client / customer" },
    "klaar": { definition: "af of gereed", translation: "ready / finished" },
    "klachten": { definition: "problemen of symptomen", translation: "complaints / symptoms" },
    "koorts": { definition: "hoge lichaamstemperatuur door ziekte", translation: "fever" },
    "koffie": { definition: "drank van koffiebonen", translation: "coffee" },
    "komen": { definition: "naar een plek gaan", translation: "to come" },
    "kort": { definition: "niet lang", translation: "short" },
    "lang": { definition: "niet kort", translation: "long" },
    "later": { definition: "na dit moment", translation: "later" },
    "leest": { definition: "bekijkt geschreven tekst", translation: "reads" },
    "leidinggevende": { definition: "persoon die jou aanstuurt op werk", translation: "manager / supervisor" },
    "lekker": { definition: "smakelijk of prettig", translation: "tasty / nice" },
    "lijken": { definition: "de indruk geven", translation: "to seem" },
    "maakt": { definition: "creëert of doet", translation: "makes" },
    "manager": { definition: "persoon die een team leidt", translation: "manager" },
    "markt": { definition: "plek waar verkopers dingen verkopen", translation: "market" },
    "me": { definition: "verkorte vorm van mij", translation: "me" },
    "meer": { definition: "een grotere hoeveelheid", translation: "more" },
    "meestal": { definition: "in de meeste gevallen", translation: "usually" },
    "met": { definition: "samen met of door middel van", translation: "with" },
    "minder": { definition: "niet zoveel", translation: "less" },
    "morgen": { definition: "de dag na vandaag", translation: "tomorrow" },
    "moet": { definition: "is nodig of verplicht", translation: "must / needs to" },
    "moe": { definition: "niet energiek", translation: "tired" },
    "na": { definition: "later dan", translation: "after" },
    "naar": { definition: "in de richting van", translation: "to / toward" },
    "niet": { definition: "ontkenning", translation: "not" },
    "nog": { definition: "op dit moment ook / extra", translation: "still / yet" },
    "om": { definition: "voor een doel of rond", translation: "to / for / around" },
    "omdat": { definition: "geeft een reden", translation: "because" },
    "onderzoek": { definition: "nauwkeurig kijken of testen", translation: "examination / research" },
    "op": { definition: "bovenop of aan", translation: "on / at" },
    "opnieuw": { definition: "nog een keer", translation: "again" },
    "paar": { definition: "klein aantal", translation: "a few / pair" },
    "park": { definition: "groene openbare plek", translation: "park" },
    "paar": { definition: "klein aantal", translation: "a few" },
    "pijn": { definition: "lichamelijk ongemak", translation: "pain" },
    "plan": { definition: "idee van wat je gaat doen", translation: "plan" },
    "planning": { definition: "overzicht van wat wanneer gebeurt", translation: "planning / schedule" },
    "plek": { definition: "plaats", translation: "place / spot" },
    "prettig": { definition: "fijn om te ervaren", translation: "pleasant" },
    "prima": { definition: "heel goed", translation: "fine / great" },
    "probleem": { definition: "iets moeilijks dat opgelost moet worden", translation: "problem" },
    "problemen": { definition: "meerdere moeilijke dingen", translation: "problems" },
    "rustig": { definition: "kalm en zonder haast", translation: "calm / quietly" },
    "samen": { definition: "met elkaar", translation: "together" },
    "slecht": { definition: "niet goed", translation: "bad / poorly" },
    "snel": { definition: "met hoge snelheid", translation: "quickly / fast" },
    "station": { definition: "plek waar trein of bus stopt", translation: "station" },
    "sturen": { definition: "verzenden", translation: "to send" },
    "tafel": { definition: "meubel met blad en poten", translation: "table" },
    "team": { definition: "groep mensen die samenwerkt", translation: "team" },
    "technische": { definition: "met techniek te maken", translation: "technical" },
    "te": { definition: "teveel of als infinitiefmarker", translation: "too / to" },
    "tijdens": { definition: "in de tijd van", translation: "during" },
    "tijd": { definition: "uren en momenten", translation: "time" },
    "toch": { definition: "ondanks alles", translation: "still / anyway" },
    "tot": { definition: "totdat of tot aan", translation: "until / to" },
    "tussen": { definition: "in het midden van twee dingen", translation: "between" },
    "uit": { definition: "naar buiten of volledig", translation: "out / off" },
    "uitleg": { definition: "verklaring waardoor iets duidelijk wordt", translation: "explanation" },
    "uren": { definition: "meerdere uren", translation: "hours" },
    "van": { definition: "behoort bij of afkomstig van", translation: "of / from" },
    "vanavond": { definition: "deze avond", translation: "this evening" },
    "vannacht": { definition: "de afgelopen nacht", translation: "last night" },
    "veel": { definition: "grote hoeveelheid", translation: "much / many / a lot" },
    "vindt": { definition: "heeft een mening of ontdekt", translation: "finds / thinks" },
    "virus": { definition: "klein organisme dat ziek kan maken", translation: "virus" },
    "vraagt": { definition: "stelt een vraag", translation: "asks" },
    "vroeg": { definition: "op een vroeg moment", translation: "early" },
    "vraag": { definition: "iets wat je wilt weten", translation: "question" },
    "vrolijk": { definition: "blij", translation: "cheerful" },
    "waarom": { definition: "met welke reden", translation: "why" },
    "wanneer": { definition: "op welk moment", translation: "when" },
    "water": { definition: "heldere vloeistof om te drinken", translation: "water" },
    "wachtkamer": { definition: "ruimte waar je wacht", translation: "waiting room" },
    "we": { definition: "eerste persoon meervoud", translation: "we" },
    "week": { definition: "periode van zeven dagen", translation: "week" },
    "werken": { definition: "arbeid doen", translation: "to work" },
    "werk": { definition: "baan of taak", translation: "work" },
    "weer": { definition: "nog een keer of het klimaat", translation: "again / weather" },
    "weg": { definition: "niet hier / route", translation: "away / road" },
    "wel": { definition: "toch / positief", translation: "indeed / yes" },
    "wil": { definition: "heeft de wens", translation: "wants" },
    "wij": { definition: "eerste persoon meervoud", translation: "we" },
    "zijn": { definition: "bestaan of behoren aan hem/haar", translation: "are / is / his" },
    "zij": { definition: "voornaamwoord voor vrouw of meervoud", translation: "she / they" },
    "zin": { definition: "wens of complete taaleenheid", translation: "desire / sentence" },
    "zo": { definition: "op deze manier / zo erg", translation: "so / like this" },
    "zodat": { definition: "met als doel dat", translation: "so that" },
    "zodra": { definition: "direct wanneer", translation: "as soon as" },
    "zolang": { definition: "gedurende de tijd dat", translation: "as long as" },
    "zonder": { definition: "niet met", translation: "without" },
    "zorg": { definition: "hulp of aandacht", translation: "care" },
    "zou": { definition: "vorm van zullen", translation: "would" }
  },
  uiCopy: {
    en: {
      heroEyebrow: "Dutch",
      heroTitle: "Learn Dutch",
      heroText: "Short daily lessons with simple word help.",
      languageLabel: "Interface language",
      darkMode: "Dark mode",
      lightMode: "Light mode",
      mainPage: "Main",
      exercisesPage: "Exercises",
      gamePage: "Game",
      wordDayLabel: "Word of the day",
      gameLabel: "Game",
      gameTitle: "Speed match",
      gameIntro: "Match the Dutch word with the correct translation as quickly as you can.",
      gameWordsTitle: "Words",
      gameMeaningsTitle: "Translations",
      newGame: "New game",
      gameScore: "Score",
      gameCorrect: "Good match.",
      gameWrong: "That pair does not match.",
      dialogueMode: "Dialogue",
      storyMode: "Story",
      lessonModeLabel: "Format",
      wordPanelLabel: "Word help",
      definitionTab: "Meaning",
      translationTab: "Translation",
      practiceLabel: "Practice",
      practiceTitle: "Use the words in context",
      fillBlankTab: "Fill blank",
      matchTab: "Match",
      contextTab: "Context",
      fillBlankTitle: "Fill in the blank",
      matchTitle: "Match word to meaning",
      contextTitle: "Choose the right word",
      saveWord: "Save word",
      savedWord: "Saved",
      masterWord: "Mark as mastered",
      masteredWord: "Mastered",
      masteredButton: "Mastered words",
      masteredTitle: "Mastered words",
      openLesson: "Open lesson",
      lessonOfDay: "Recommended for today",
      lessonModeDialogue: "Dialogue",
      lessonModeStory: "Mini story",
      emptyWordTitle: "Click a word",
      emptyWordIntro:
        "Select a highlighted word in the text to see a simple explanation in Dutch.",
      reviewIntro:
        "Saved words and weak words should come back later in new lessons and review sessions.",
      savedWordsEmpty: "No saved words yet.",
      masteredWordsEmpty: "No mastered words yet.",
      correct: "Correct. This fits the sentence well.",
      wrongPrefix: "Not this one. Correct answer:",
      situationGroups: [
        "Meeting a friend",
        "At a cafe or bar",
        "Doctor and health",
        "At work",
        "Phone calls",
        "Shopping and supermarket",
        "Public transport",
        "Gemeente and forms",
        "Neighbors",
        "Weekend plans"
      ]
    },
    nl: {
      heroEyebrow: "Nederlands",
      heroTitle: "Leer Nederlands",
      heroText: "Korte dagelijkse lessen met eenvoudige woordhulp.",
      languageLabel: "Taal van de interface",
      darkMode: "Donkere modus",
      lightMode: "Lichte modus",
      todayLabel: "Les van vandaag",
      continueLabel: "Ga verder",
      mainPage: "Hoofd",
      exercisesPage: "Oefeningen",
      gamePage: "Spel",
      wordDayLabel: "Woord van de dag",
      gameLabel: "Spel",
      gameTitle: "Snel koppelen",
      gameIntro: "Koppel het Nederlandse woord aan de juiste vertaling.",
      gameWordsTitle: "Woorden",
      gameMeaningsTitle: "Vertalingen",
      newGame: "Nieuw spel",
      gameScore: "Score",
      gameCorrect: "Goed gekoppeld.",
      gameWrong: "Deze combinatie klopt niet.",
      dialogueMode: "Dialoog",
      storyMode: "Verhaal",
      lessonModeLabel: "Vorm",
      wordPanelLabel: "Woordhulp",
      definitionTab: "Betekenis",
      translationTab: "Vertaling",
      practiceLabel: "Oefenen",
      practiceTitle: "Gebruik de woorden in context",
      fillBlankTab: "Invullen",
      matchTab: "Koppelen",
      contextTab: "Context",
      fillBlankTitle: "Vul het juiste woord in",
      matchTitle: "Koppel woord aan betekenis",
      contextTitle: "Kies het juiste woord",
      saveWord: "Woord opslaan",
      savedWord: "Opgeslagen",
      masterWord: "Beheerst",
      masteredWord: "Beheerst",
      masteredButton: "Beheerste woorden",
      masteredTitle: "Beheerste woorden",
      openLesson: "Open les",
      lessonOfDay: "Aanbevolen voor vandaag",
      lessonModeDialogue: "Dialoog",
      lessonModeStory: "Mini-verhaal",
      emptyWordTitle: "Klik op een woord",
      emptyWordIntro:
        "Selecteer een gemarkeerd woord in de tekst om een eenvoudige uitleg in het Nederlands te zien.",
      reviewIntro:
        "Opgeslagen woorden en zwakke woorden moeten later terugkomen in nieuwe lessen en herhaalsessies.",
      savedWordsEmpty: "Nog geen opgeslagen woorden.",
      masteredWordsEmpty: "Nog geen beheerste woorden.",
      correct: "Goed. Dit past goed in de zin.",
      wrongPrefix: "Nog niet goed. Juiste antwoord:",
      situationGroups: [
        "Met een vriend afspreken",
        "In een cafe of bar",
        "Dokter en gezondheid",
        "Op het werk",
        "Telefoongesprekken",
        "Winkelen en supermarkt",
        "Openbaar vervoer",
        "Gemeente en formulieren",
        "Buren",
        "Weekendplannen"
      ]
    }
  },
  lessons: [
    {
      id: "meet-friend-dialogue",
      level: "A1",
      mode: "dialogue",
      theme: "social",
      title: {
        en: "Meeting a friend in town",
        nl: "Een vriend ontmoeten in de stad"
      },
      intro: {
        en: "A short social dialogue with simple plans, places, and timing.",
        nl: "Een korte sociale dialoog met eenvoudige plannen, plekken en tijden."
      },
      sentences: [
        "Mila: Hoi Sam, heb je vanavond tijd om iets te drinken in de stad?",
        "Sam: Ja, dat lijkt me gezellig, maar ik werk eerst nog tot zes uur.",
        "Mila: Geen probleem, dan kunnen we om half zeven bij het station afspreken.",
        "Sam: Prima, zal ik daarna een tafel zoeken in dat kleine cafe bij het plein?",
        "Mila: Ja, graag, want daar is het meestal rustig en de koffie is lekker.",
        "Sam: Wil je alleen koffie of ook iets eten?",
        "Mila: Misschien later, want ik heb thuis al een broodje gegeten.",
        "Sam: Goed, ik stuur je nog een bericht als ik uit mijn werk vertrek.",
        "Mila: Fijn, dan weet ik precies wanneer ik moet gaan.",
        "Sam: Tot straks, ik heb er zin in."
      ],
      focusWords: {
        gezellig: {
          definition: "prettig, warm en fijn om samen te zijn",
          translation: "cozy / pleasant / nice together",
          example: "Het was een gezellige avond met vrienden.",
          funSentence: "Met een warme thee en goede vrienden voelt zelfs regenachtig weer gezellig."
        },
        afspreken: {
          definition: "met iemand plannen om elkaar op een bepaald moment te zien",
          translation: "to meet / to arrange",
          example: "Wij spreken morgen af in het park.",
          funSentence: "Als we op tijd afspreken, komt niemand als laatste aan op het terras."
        },
        vertrek: {
          definition: "wegga van een plek om ergens anders naartoe te gaan",
          translation: "depart / leave",
          example: "De trein vertrekt om acht uur.",
          funSentence: "Mijn vertrek is altijd stressvol als ik mijn sleutels weer niet kan vinden."
        },
        plein: {
          definition: "open plek in een stad of dorp met gebouwen eromheen",
          translation: "square / plaza",
          example: "Op het plein staan veel fietsen.",
          funSentence: "Op het plein hoor je vaak muziek, gesprekken en een paar luide meeuwen."
        }
      },
      exercises: {
        fillBlank: {
          prompt: "Mila en Sam willen om half zeven bij het station _____.",
          choices: ["afspreken", "repareren", "vergeten"],
          answer: "afspreken"
        },
        match: {
          prompt: "Welke betekenis hoort bij 'gezellig'?",
          choices: [
            "prettig en fijn om samen te zijn",
            "heel duur en officieel",
            "druk en vermoeiend"
          ],
          answer: "prettig en fijn om samen te zijn"
        },
        context: {
          prompt: "De trein _____ over vijf minuten van spoor 3.",
          choices: ["vertrekt", "betaalt", "wachtkamer"],
          answer: "vertrekt"
        }
      }
    },
    {
      id: "doctor-story",
      level: "A2",
      mode: "story",
      theme: "health",
      title: {
        en: "A visit to the doctor",
        nl: "Een bezoek aan de dokter"
      },
      intro: {
        en: "A practical mini story about symptoms, advice, and daily routine.",
        nl: "Een praktisch mini-verhaal over klachten, advies en dagelijkse routine."
      },
      sentences: [
        "Yara voelt zich al twee dagen moe en heeft pijn in haar keel.",
        "Omdat de klachten niet minder worden, maakt zij een afspraak bij de huisarts.",
        "In de wachtkamer leest zij rustig een folder over gezond slapen.",
        "De arts vraagt wanneer de klachten zijn begonnen en of Yara ook koorts heeft gehad.",
        "Yara vertelt dat zij slecht heeft geslapen en bijna geen eetlust had.",
        "Na het onderzoek denkt de arts dat het waarschijnlijk een virus is.",
        "Hij adviseert haar om veel water te drinken en een paar dagen rustig aan te doen.",
        "Ook zegt hij dat zij opnieuw moet bellen als de klachten erger worden.",
        "Thuis stuurt Yara haar collega een kort bericht dat zij morgen niet kan werken.",
        "Daarna maakt zij thee en gaat zij vroeg naar bed."
      ],
      focusWords: {
        klachten: {
          definition: "problemen of pijn die je voelt in je lichaam of in een situatie",
          translation: "complaints / symptoms",
          example: "Welke klachten heb je precies?",
          funSentence: "Mijn enige klacht vandaag is dat de koffie op was voordat ik wakker werd."
        },
        eetlust: {
          definition: "zin om te eten",
          translation: "appetite",
          example: "Door de warmte had ik weinig eetlust.",
          funSentence: "Na een lange wandeling komt mijn eetlust altijd snel terug."
        },
        adviseert: {
          definition: "zegt wat volgens hem of haar verstandig is om te doen",
          translation: "advises / recommends",
          example: "De docent adviseert mij om meer te lezen.",
          funSentence: "Mijn moeder adviseert altijd om eerst te eten en dan pas moeilijke beslissingen te nemen."
        },
        erger: {
          definition: "meer vervelend, meer pijnlijk of slechter dan eerst",
          translation: "worse",
          example: "De pijn werd in de avond erger.",
          funSentence: "Zonder muziek wordt schoonmaken voor mij alleen maar erger."
        }
      },
      exercises: {
        fillBlank: {
          prompt: "De arts _____ Yara om veel water te drinken.",
          choices: ["adviseert", "betaalt", "verzamelt"],
          answer: "adviseert"
        },
        match: {
          prompt: "Welke betekenis hoort bij 'eetlust'?",
          choices: [
            "zin om te eten",
            "angst voor de dokter",
            "tijd om naar huis te gaan"
          ],
          answer: "zin om te eten"
        },
        context: {
          prompt: "Als je klachten _____ worden, moet je opnieuw bellen.",
          choices: ["erger", "vriendelijk", "digitaal"],
          answer: "erger"
        }
      }
    },
    {
      id: "work-meeting-story",
      level: "B1",
      mode: "story",
      theme: "work",
      title: {
        en: "A meeting that changes the plan",
        nl: "Een overleg dat het plan verandert"
      },
      intro: {
        en: "A workplace reading about planning, expectations, and making a realistic decision.",
        nl: "Een leestekst over planning, verwachtingen en een realistische beslissing nemen."
      },
      sentences: [
        "Karim werkt in een team dat een nieuwe website maakt voor een grote klant.",
        "Tijdens het wekelijkse overleg merkt hij dat de planning te ambitieus is geworden.",
        "Een paar collega's denken dat alles nog op tijd af kan zijn, maar Karim twijfelt daaraan.",
        "Hij legt uit dat er nog technische problemen zijn die meer aandacht nodig hebben.",
        "Zijn leidinggevende vraagt of het team extra uren wil maken om de deadline te halen.",
        "Karim begrijpt de druk, maar hij wil ook eerlijk blijven over de risico's.",
        "Na een lang gesprek besluit het team om eerst de belangrijkste onderdelen af te ronden.",
        "Minder belangrijke functies worden naar de volgende versie verschoven.",
        "De klant reageert uiteindelijk begripvol, omdat een stabiel product belangrijker is dan haast.",
        "Karim voelt zich opgelucht, want het nieuwe plan is duidelijker en beter uitvoerbaar."
      ],
      focusWords: {
        ambitieus: {
          definition: "zo groot of moeilijk dat er veel werk nodig is om het te halen",
          translation: "ambitious",
          example: "Dat is een ambitieus plan voor zo'n klein team.",
          funSentence: "Het is ambitieus om op maandagmorgen tegelijk fit, vrolijk en perfect voorbereid te zijn."
        },
        deadline: {
          definition: "de uiterste datum of tijd waarop iets klaar moet zijn",
          translation: "deadline",
          example: "De deadline is volgende week vrijdag.",
          funSentence: "Een deadline lijkt altijd sneller te lopen zodra je net koffie hebt gehaald."
        },
        begripvol: {
          definition: "laten zien dat je de situatie van iemand anders goed begrijpt",
          translation: "understanding / sympathetic",
          example: "Mijn manager was begripvol toen ik ziek was.",
          funSentence: "Een begripvolle collega maakt een drukke werkdag meteen lichter."
        },
        uitvoerbaar: {
          definition: "mogelijk om echt te doen of uit te voeren",
          translation: "feasible / workable",
          example: "Nu is het plan veel beter uitvoerbaar.",
          funSentence: "Tien dingen tegelijk plannen klinkt slim, maar meestal is dat niet uitvoerbaar."
        }
      },
      exercises: {
        fillBlank: {
          prompt: "Karim wil eerlijk blijven over de _____ van het plan.",
          choices: ["risico's", "aardbeien", "jassen"],
          answer: "risico's"
        },
        match: {
          prompt: "Welke betekenis hoort bij 'uitvoerbaar'?",
          choices: [
            "mogelijk om echt uit te voeren",
            "vol met fouten en problemen",
            "heel snel klaar"
          ],
          answer: "mogelijk om echt uit te voeren"
        },
        context: {
          prompt: "De klant reageerde _____ en begreep waarom meer tijd nodig was.",
          choices: ["begripvol", "duizelig", "plotseling"],
          answer: "begripvol"
        }
      }
    }
  ]
};
